require: rubocop-performance

AllCops:
  TargetRubyVersion: 2.7.1
  NewCops: enable

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Security/MarshalLoad:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FormatStringToken:
  EnforcedStyle: unannotated

Style/FrozenStringLiteralComment:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/SpecialGlobalVars:
  EnforcedStyle: use_perl_names

Style/YodaCondition:
  EnforcedStyle: forbid_for_equality_operators_only
