require: rubocop-performance

AllCops:
  TargetRubyVersion: 2.7.1
  NewCops: enable

Lint/AmbiguousBlockAssociation:
  Enabled: false

Lint/AmbiguousOperator:
  Enabled: false

Metrics/MethodLength:
  Max: 14

Naming/MethodParameterName:
  MinNameLength: 1

Security/MarshalLoad:
  Enabled: false

Style/FormatStringToken:
  EnforcedStyle: unannotated

Style/FrozenStringLiteralComment:
  Enabled: false

Style/NumericPredicate:
  Enabled: false
